eureka:
  instance:
    hostname: authentication-service
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

spring:
    application:
        name: authentication-service

    #Database PostrgreSQL
    datasource:
      username: auth_user
      password: auth_password
      driver-class-name: org.postgresql.Driver
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: create
      show-sql: true

    kafka:
      bootstrap-servers: kafka:9092
      consumer:
        group-id: email-group

#Security
security:
  jwt:
    secret_key: c39d70463be1a5a035db4cf1f655d59434cdc5c34b29f1c25bc6a21ad3c25e22
    access_token_expiration: 3600000 # 1 hours
    refresh_token_expiration: 604800000 # 7 days

logging:
  level:
    org.springframework.web: DEBUG
  file:
    name: logs/authentication-service.log

server:
  servlet:
    context-path: /api/v1

  port: 8081

springdoc:
  api-docs:
    enabled: true
    path: /auth/v3/api-docs
  swagger-ui:
    enabled: true
    path: /auth/swagger-ui.html

